name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "verifying images:"
          docker images

      - name: Deploy to minikube
        run: |
          kubectl apply -f k8s-node-app.yaml
          kubectl rollout status deployment/nodejs-app --timeout=90s

      - name: Test service URLs
        run: |
          sleep 10
          minikube service list
          minikube service nodejs-app --url
